In [4]:
import pandas as pd
import numpy as np
import random

names = ['Mohammed', 'Abdul', 'shaik', 'sharukh', 'Fareeha', 'Javeed', 'Khaled', 'Shaziya', 'Jabbar', 'Neha']

genders = ['Male', 'Male', 'Male', 'Male', 'female', 'Male', 'Male','female', 'Male', 'female',]


ages = [random.randint(21, 25) for _ in range(10)]
marks = [random.randint(60, 95) for _ in range(10)]
subjects = random.choices(['Python', 'statistics', 'Generative AI'], k=10)

df =pd.DataFrame({
    'Name' : names,
    'Gender' : genders,
    'ages' : ages,
    'marks' : marks,
    'subjects' :subjects
})

df

       Name  Gender  ages  marks       subjects
0  Mohammed    Male    21     61     statistics
1     Abdul    Male    23     76  Generative AI
2     shaik    Male    22     69         Python
3   sharukh    Male    22     86         Python
4   Fareeha  female    21     79     statistics
5    Javeed    Male    22     90         Python
6    Khaled    Male    21     92     statistics
7   Shaziya  female    21     73  Generative AI
8    Jabbar    Male    22     66  Generative AI
9      Neha  female    25     66  Generative AI

In [6]:
df.shape

(10, 5)

In [7]:
df.describe().round(2)

        ages  marks
count  10.00   10.0
mean   23.20   82.2
std     1.23    9.4
min    21.00   60.0
25%    23.00   79.0
50%    23.00   83.0
75%    23.75   86.0
max    25.00   94.0

In [9]:
df.describe(include = "object")

            Name Gender subjects
count         10     10       10
unique        10      2        3
top     Mohammed   Male   Python
freq           1      7        4

In [10]:
type(df['marks'])

pandas.core.series.Series

In [14]:
df[['marks', 'Name']]

   marks      Name
0     86  Mohammed
1     60     Abdul
2     92     shaik
3     86   sharukh
4     82   Fareeha
5     78    Javeed
6     78    Khaled
7     94   Shaziya
8     84    Jabbar
9     82      Neha

In [16]:
df[df['marks'] > 80]

       Name  Gender  ages  marks       subjects
0  Mohammed    Male    23     86         Python
2     shaik    Male    25     92         Python
3   sharukh    Male    23     86     statistics
4   Fareeha  female    23     82  Generative AI
7   Shaziya  female    21     94         Python
8    Jabbar    Male    25     84  Generative AI
9      Neha  female    23     82     statistics

In [3]:
df['Double_Marks'] = df['marks'] * 2

NameError: name 'df' is not defined

In [7]:
df['Double Marks'] = df['marks'] * 2

In [8]:
df

       Name  Gender  ages  marks       subjects  Double Marks
0  Mohammed    Male    21     61     statistics           122
1     Abdul    Male    23     76  Generative AI           152
2     shaik    Male    22     69         Python           138
3   sharukh    Male    22     86         Python           172
4   Fareeha  female    21     79     statistics           158
5    Javeed    Male    22     90         Python           180
6    Khaled    Male    21     92     statistics           184
7   Shaziya  female    21     73  Generative AI           146
8    Jabbar    Male    22     66  Generative AI           132
9      Neha  female    25     66  Generative AI           132

In [9]:
df['marks'] = df['marks'].apply(lambda x: x + 5)

In [10]:
df

       Name  Gender  ages  marks       subjects  Double Marks
0  Mohammed    Male    21     66     statistics           122
1     Abdul    Male    23     81  Generative AI           152
2     shaik    Male    22     74         Python           138
3   sharukh    Male    22     91         Python           172
4   Fareeha  female    21     84     statistics           158
5    Javeed    Male    22     95         Python           180
6    Khaled    Male    21     97     statistics           184
7   Shaziya  female    21     78  Generative AI           146
8    Jabbar    Male    22     71  Generative AI           132
9      Neha  female    25     71  Generative AI           132

In [13]:
df = df.rename(columns={'marks' : 'Updated_Marks'})
df

       Name  Gender  ages  Updated_Marks       subjects  Double Marks
0  Mohammed    Male    21             66     statistics           122
1     Abdul    Male    23             81  Generative AI           152
2     shaik    Male    22             74         Python           138
3   sharukh    Male    22             91         Python           172
4   Fareeha  female    21             84     statistics           158
5    Javeed    Male    22             95         Python           180
6    Khaled    Male    21             97     statistics           184
7   Shaziya  female    21             78  Generative AI           146
8    Jabbar    Male    22             71  Generative AI           132
9      Neha  female    25             71  Generative AI           132